(defun visual/init ()
  (load "~/.cache/wal/colors.lisp")       ; Generated by pywal
  (set-bg-color background)
  (set-fg-color foreground)

  (set-border-color color1)
  (set-win-bg-color color1)

  (set-focus-color color1)
  (set-unfocus-color background)

  ;; Doesn't change the color at start (??) TODO
  (set-float-focus-color color1)
  (set-float-unfocus-color background))
