#ifndef COLORS_H
#define COLORS_H

/* Generated by pywal */

static const char* wallpaper = "{wallpaper}";

static const char* background = "{background}";
static const char* foreground = "{foreground}";
static const char* cursor = "{cursor}";

static const char* colors[] = {{
  "{color0}",
  "{color1}",
  "{color2}",
  "{color3}",
  "{color4}",
  "{color5}",
  "{color6}",
  "{color7}",
  "{color8}",
  "{color9}",
  "{color10}",
  "{color11}",
  "{color12}",
  "{color13}",
  "{color14}",
  "{color15}",
}};

#endif /* COLORS_H */
