; Lisp variables
; Generated by 'wal'
(setq wallpaper "{wallpaper}")

; Special
(setq background "{background}")
(setq foreground "{foreground}")
(setq cursor "{cursor}")

; Colors
(setq color0 "{color0}")
(setq color1 "{color1}")
(setq color2 "{color2}")
(setq color3 "{color3}")
(setq color4 "{color4}")
(setq color5 "{color5}")
(setq color6 "{color6}")
(setq color7 "{color7}")
(setq color8 "{color8}")
(setq color9 "{color9}")
(setq color10 "{color10}")
(setq color11 "{color11}")
(setq color12 "{color12}")
(setq color13 "{color13}")
(setq color14 "{color14}")
(setq color15 "{color15}")
