#ifndef COLORS_H
#define COLORS_H

/* Generated by pywal */
static const char *colors[] = {{
  "{background}", /* focuscol */
  "{background}", /* unfocuscol */
	"#ffffff",      /* fixedcol */
	"#ffffff",      /* unkilcol */
	"#ffffff",      /* fixedunkilcol */
	"{foreground}", /* outerbordercol */
	"#000000"       /* emptycol */
}};

#endif /* COLORS_H */
