#!/bin/sh

# Theme changer. Relinks pywal cache.

#set -e

# Set those values by hand
WALL="/home/jarmusz/other/wallpapers/cat.png"
# Note the use of ${HOME}; unlink doesn't seem to expand the `~'
DARK="${HOME}/.cache/wal/schemes/cat_dark.json"
LIGHT="${HOME}/.cache/wal/schemes/cat_light.json"

TARGET="${HOME}/.cache/wal/schemes/`echo $WALL | sed 's/\//_/g; s/\./_/g'`_dark_None_None_1.1.0.json"

switch() {
	echo $1
	unlink $TARGET
	ln -s $1 "$TARGET"
	wal -i "$WALL"
	pkill -1 cwm
	killall lemonbar
	REVERSE=$2 ~/.scripts/cwmbar.sh | lemonbar -f "iosevka-11" > /dev/null &
}

case "$1" in
	d) switch "$DARK"
		;;
	l) switch "$LIGHT" yes
		;;
	r) [ "`readlink $TARGET`" = "$DARK" ] &&
			$0 d	||
			$0 l
		 ;;
	*) if [ "`readlink $TARGET`" = "$DARK" ]; then
			echo light
			switch "$LIGHT" yes
		else
			echo dark
			switch "$DARK"
	fi
esac
