#!/bin/bash
# Not POSIX complaint - read -a

[ -z "$(mpc current 2>/dev/null)" ] && exit 1

# I may be dumb but this works
export IFS=":"
read -ra arr <<EOF
$(mpc current -f "%title%:%artist%:%album%")
EOF

cat <<EOF
now playing ♪
song:  ${arr[0]}
by:    ${arr[1]}
album: ${arr[2]}
EOF
